//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsImperio.ServiceReferenceImperio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceImperio.WebServiceImperioSoap")]
    public interface WebServiceImperioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rebeldes del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarRebeldes", ReplyAction="*")]
        WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesResponse InsertarRebeldes(WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarRebeldes", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesResponse> InsertarRebeldesAsync(WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerRebeldesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerRebeldes", ReplyAction="*")]
        WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesResponse ObtenerRebeldes(WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerRebeldes", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesResponse> ObtenerRebeldesAsync(WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarRebeldesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarRebeldes", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesRequestBody Body;
        
        public InsertarRebeldesRequest() {
        }
        
        public InsertarRebeldesRequest(WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarRebeldesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsImperio.ServiceReferenceImperio.ArrayOfString rebeldes;
        
        public InsertarRebeldesRequestBody() {
        }
        
        public InsertarRebeldesRequestBody(WindowsFormsImperio.ServiceReferenceImperio.ArrayOfString rebeldes) {
            this.rebeldes = rebeldes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarRebeldesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarRebeldesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesResponseBody Body;
        
        public InsertarRebeldesResponse() {
        }
        
        public InsertarRebeldesResponse(WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarRebeldesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertarRebeldesResult;
        
        public InsertarRebeldesResponseBody() {
        }
        
        public InsertarRebeldesResponseBody(bool InsertarRebeldesResult) {
            this.InsertarRebeldesResult = InsertarRebeldesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerRebeldesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerRebeldes", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesRequestBody Body;
        
        public ObtenerRebeldesRequest() {
        }
        
        public ObtenerRebeldesRequest(WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerRebeldesRequestBody {
        
        public ObtenerRebeldesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerRebeldesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerRebeldesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesResponseBody Body;
        
        public ObtenerRebeldesResponse() {
        }
        
        public ObtenerRebeldesResponse(WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerRebeldesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsImperio.ServiceReferenceImperio.ArrayOfString ObtenerRebeldesResult;
        
        public ObtenerRebeldesResponseBody() {
        }
        
        public ObtenerRebeldesResponseBody(WindowsFormsImperio.ServiceReferenceImperio.ArrayOfString ObtenerRebeldesResult) {
            this.ObtenerRebeldesResult = ObtenerRebeldesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceImperioSoapChannel : WindowsFormsImperio.ServiceReferenceImperio.WebServiceImperioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceImperioSoapClient : System.ServiceModel.ClientBase<WindowsFormsImperio.ServiceReferenceImperio.WebServiceImperioSoap>, WindowsFormsImperio.ServiceReferenceImperio.WebServiceImperioSoap {
        
        public WebServiceImperioSoapClient() {
        }
        
        public WebServiceImperioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceImperioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceImperioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceImperioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesResponse WindowsFormsImperio.ServiceReferenceImperio.WebServiceImperioSoap.InsertarRebeldes(WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesRequest request) {
            return base.Channel.InsertarRebeldes(request);
        }
        
        public bool InsertarRebeldes(WindowsFormsImperio.ServiceReferenceImperio.ArrayOfString rebeldes) {
            WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesRequest inValue = new WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesRequest();
            inValue.Body = new WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesRequestBody();
            inValue.Body.rebeldes = rebeldes;
            WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesResponse retVal = ((WindowsFormsImperio.ServiceReferenceImperio.WebServiceImperioSoap)(this)).InsertarRebeldes(inValue);
            return retVal.Body.InsertarRebeldesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesResponse> WindowsFormsImperio.ServiceReferenceImperio.WebServiceImperioSoap.InsertarRebeldesAsync(WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesRequest request) {
            return base.Channel.InsertarRebeldesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesResponse> InsertarRebeldesAsync(WindowsFormsImperio.ServiceReferenceImperio.ArrayOfString rebeldes) {
            WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesRequest inValue = new WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesRequest();
            inValue.Body = new WindowsFormsImperio.ServiceReferenceImperio.InsertarRebeldesRequestBody();
            inValue.Body.rebeldes = rebeldes;
            return ((WindowsFormsImperio.ServiceReferenceImperio.WebServiceImperioSoap)(this)).InsertarRebeldesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesResponse WindowsFormsImperio.ServiceReferenceImperio.WebServiceImperioSoap.ObtenerRebeldes(WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesRequest request) {
            return base.Channel.ObtenerRebeldes(request);
        }
        
        public WindowsFormsImperio.ServiceReferenceImperio.ArrayOfString ObtenerRebeldes() {
            WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesRequest inValue = new WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesRequest();
            inValue.Body = new WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesRequestBody();
            WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesResponse retVal = ((WindowsFormsImperio.ServiceReferenceImperio.WebServiceImperioSoap)(this)).ObtenerRebeldes(inValue);
            return retVal.Body.ObtenerRebeldesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesResponse> WindowsFormsImperio.ServiceReferenceImperio.WebServiceImperioSoap.ObtenerRebeldesAsync(WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesRequest request) {
            return base.Channel.ObtenerRebeldesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesResponse> ObtenerRebeldesAsync() {
            WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesRequest inValue = new WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesRequest();
            inValue.Body = new WindowsFormsImperio.ServiceReferenceImperio.ObtenerRebeldesRequestBody();
            return ((WindowsFormsImperio.ServiceReferenceImperio.WebServiceImperioSoap)(this)).ObtenerRebeldesAsync(inValue);
        }
    }
}
